# Generated by Django 2.2 on 2020-07-25 15:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_auto_20200725_1828'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique posts_follow',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'author')},
        ),
        migrations.AlterModelTable(
            name='follow',
            table=None,
        ),
    ]
